ProjekatPPP/Models/IznajmljeneFilm.cs
namespace ProjekatPPP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("IznajmljeneFilm")]
    public partial class IznajmljeneFilm
    {
        [Key]
        [Column(Order = 0)]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int RedniBrojIznajmljivanja { get; set; }

        [Column(Order = 1)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int RedniBrojČlana { get; set; }

        [Key]
        [Column(Order = 2)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int SifraFilma { get; set; }

        [Required]
        [StringLength(50)]
        public string Naziv { get; set; }

        [Required]
        [StringLength(30)]
        public string Reziser { get; set; }

        [Column(TypeName = "date")]
        public DateTime Datum { get; set; }

        public int Kolicina { get; set; }
    }
}

ProjekatPPP/Controllers/IznajmljeneFilmsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjekatPPP.Models;
using PagedList;

namespace ProjekatPPP.Controllers
{
    public class IznajmljeneFilmsController : Controller
    {
        private KinotekaContext db = new KinotekaContext();

        // GET: IznajmljeneFilms
        public ActionResult Index(int? strana)
        {
            var brojStrane = strana ?? 1;
            var velicinaStrane = 5;
            var iznajmljeneFilme = db.IznajmljeneFilms.OrderBy(i => i.RedniBrojIznajmljivanja).ToPagedList(brojStrane, velicinaStrane);
            return View(iznajmljeneFilme);
        
        }

        // GET: IznajmljeneFilms/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IznajmljeneFilm iznajmljeneFilma = db.IznajmljeneFilms.Find(id);
            if (iznajmljeneFilma == null)
            {
                return HttpNotFound();
            }
            return View(iznajmljeneFilma);
        }

        // GET: IznajmljeneFilms/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: IznajmljeneFilms/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RedniBrojIznajmljivanja,RedniBrojČlana,SifraFilma,Naziv,Reziser,Datum,Kolicina")] IznajmljeneFilm iznajmljeneFilma)
        {
            if (ModelState.IsValid)
            {
                db.IznajmljeneFilms.Add(iznajmljeneFilma);
                db.SaveChanges();
                return RedirectToAction("Index", "IznajmljeneFilms");
            }

            return View(iznajmljeneFilma);
        }

        // GET: IznajmljeneFilms/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IznajmljeneFilm iznajmljeneFilma = db.IznajmljeneFilms.Find(id);
            if (iznajmljeneFilma == null)
            {
                return HttpNotFound();
            }
            return View(iznajmljeneFilma);
        }

        // POST: IznajmljeneFilms/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RedniBrojIznajmljivanja,RedniBrojČlana,SifraFilma,Naziv,Reziser,Datum,Kolicina")] IznajmljeneFilm iznajmljeneFilma)
        {
            if (ModelState.IsValid)
            {
                db.Entry(iznajmljeneFilma).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(iznajmljeneFilma);
        }

        // GET: IznajmljeneFilms/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IznajmljeneFilm iznajmljeneFilma = db.IznajmljeneFilms.Where(i => i.RedniBrojIznajmljivanja == id).FirstOrDefault();
            if (iznajmljeneFilma == null)
            {
                return HttpNotFound();
            }
            return View(iznajmljeneFilma);
        }

        // POST: IznajmljeneFilms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            IznajmljeneFilm iznajmljeneFilma = db.IznajmljeneFilms.Where(i => i.RedniBrojIznajmljivanja == id).FirstOrDefault();
            db.IznajmljeneFilms.Remove(iznajmljeneFilma);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult Rezervacija(int id)
        {
            Film film = db.Films.Find(id);

            IznajmljeneFilm iznamljivanje = new IznajmljeneFilm();

            iznamljivanje.SifraFilma = film.SifraFilma;
            iznamljivanje.RedniBrojČlana = (int)Session["IdKorisnika"];
            iznamljivanje.Naziv = film.Naziv;
            iznamljivanje.Reziser = film.Reziser;
            iznamljivanje.Datum = DateTime.Now;
            iznamljivanje.Kolicina = 1;

            try
            {
                db.IznajmljeneFilms.Add(iznamljivanje);
                db.SaveChanges();
                return RedirectToAction("Index", "IznajmljeneFilms");
            }
            catch (Exception)
            {
                return View("Error");
            }
        }
    }
}

ProjekatPPP/Controllers/KorisniksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjekatPPP.Models;

namespace ProjekatPPP.Controllers
{
    public class KorisniksController : Controller
    {
        private KinotekaContext db = new KinotekaContext();

        // GET: Korisniks
        public ActionResult Index()
        {
            return View(db.Korisniks.ToList());
        }

        // GET: Korisniks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Korisnik korisnik = db.Korisniks.Find(id);
            if (korisnik == null)
            {
                return HttpNotFound();
            }
            return View(korisnik);
        }

        // GET: Korisniks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Korisniks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RedniBroj,Email,Ime,Prezime,Adresa,Šifra,TipKorisnika")] Korisnik korisnik)
        {
            if (ModelState.IsValid)
            {
                db.Korisniks.Add(korisnik);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(korisnik);
        }

        // GET: Korisniks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Korisnik korisnik = db.Korisniks.Find(id);
            if (korisnik == null)
            {
                return HttpNotFound();
            }
            return View(korisnik);
        }

        // POST: Korisniks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RedniBroj,Email,Ime,Prezime,Adresa,Šifra,PotvrdaŠifre")] Korisnik korisnik)
        {
            if (ModelState.IsValid)
            {
                db.Entry(korisnik).State = EntityState.Modified;
                db.SaveChanges();
                Session["Ime"] = korisnik.Ime;
                return RedirectToAction("Index", "Films");
            }
            return View(korisnik);
        }

        // GET: Korisniks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Korisnik korisnik = db.Korisniks.Find(id);
            if (korisnik == null)
            {
                return HttpNotFound();
            }
            return View(korisnik);
        }

        // POST: Korisniks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Korisnik korisnik = db.Korisniks.Find(id);
            db.Korisniks.Remove(korisnik);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult Registracija()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RegistracijaKorisnika([Bind(Include = "RedniBroj,Email,Ime,Prezime,Adresa,Šifra,PotvrdaŠifre,TipKorisnika")] Korisnik korisnik)
        {
            if (ModelState.IsValid)
            {
                var podaciOKorisniku = db.Korisniks.Where(x => x.Email == korisnik.Email).SingleOrDefault();
                if (podaciOKorisniku == null)
                {
                    Korisnik noviKorisnik = korisnik;
                    db.Korisniks.Add(noviKorisnik);
                    db.SaveChanges();
                    Session["IdKorisnika"] = noviKorisnik.RedniBroj;
                    Session["Ime"] = noviKorisnik.Ime;
                    return RedirectToAction("Index", "Films");
                }
                else
                {
                    ViewBag.Greska = "Postoji korisnik sa istom Email adresom. Molimo Vas izaberite drugu.";
                    return View("Registracija");
                }
            }
            else
            {
                return View("Registracija");
            }
        }

        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Reziserizacija(Korisnik korisnik)
        {
            var podaciOKorisniku = db.Korisniks.Where(x => x.Email == korisnik.Email && x.Šifra == korisnik.Šifra).FirstOrDefault();
            if(podaciOKorisniku == null)
            {
                ViewBag.Greska = "Proverite unetu Email adresu i šifru.";
                return View("Login");
            }
            else
            {
                Session["IdKorisnika"] = podaciOKorisniku.RedniBroj;
                Session["Ime"] = podaciOKorisniku.Ime;
                return RedirectToAction("Index", "Films");
            }
        }

        public ActionResult Odjava()
        {
            Session.Abandon();
            return RedirectToAction("Index", "Home");
        }
    }
}

ProjekatPPP/Views/IznajmljeneFilms/Create.cshtml
@model ProjekatPPP.Models.IznajmljeneFilm

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>IznajmljeneFilm</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RedniBrojIznajmljivanja, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RedniBrojIznajmljivanja, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RedniBrojIznajmljivanja, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RedniBrojČlana, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RedniBrojČlana, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RedniBrojČlana, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SifraFilma, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SifraFilma, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SifraFilma, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Reziser, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Reziser, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Reziser, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Datum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Datum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Datum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Kolicina, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Kolicina, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Kolicina, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProjekatPPP/Views/IznajmljeneFilms/Delete.cshtml
@model ProjekatPPP.Models.IznajmljeneFilm

@{
    ViewBag.Title = "Brisanje";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Da li ste sigurni da želite da obrišete ovu rezervaciju?</h3>
<div>
    <h4>Film</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Reziser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Reziser)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Datum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Datum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Kolicina)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kolicina)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Obriši" class="btn btn-danger" /> |
            @Html.ActionLink("Vrati se na rezervacije", "Index")
        </div>
    }
</div>

ProjekatPPP/Views/IznajmljeneFilms/Details.cshtml
@model ProjekatPPP.Models.IznajmljeneFilm

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>IznajmljeneFilm</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Reziser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Reziser)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Datum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Datum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Kolicina)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kolicina)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ProjekatPPP/Views/IznajmljeneFilms/Edit.cshtml
@model ProjekatPPP.Models.IznajmljeneFilm

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>IznajmljeneFilm</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.RedniBrojIznajmljivanja)

        @Html.HiddenFor(model => model.RedniBrojČlana)

        @Html.HiddenFor(model => model.SifraFilma)

        <div class="form-group">
            @Html.LabelFor(model => model.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Reziser, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Reziser, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Reziser, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Datum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Datum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Datum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Kolicina, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Kolicina, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Kolicina, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProjekatPPP/Views/IznajmljeneFilms/Index.cshtml
@*@model IEnumerable<ProjekatPPP.Models.IznajmljeneFilm>*@
@using ProjekatPPP.Models;
@using PagedList;
@using PagedList.Mvc;
@model PagedList.IPagedList<ProjekatPPP.Models.IznajmljeneFilm>
@{
    ViewBag.Title = "Profil";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.ActionLink("Promeni lične podatke", "Edit", "Korisniks", new { id = (int)Session["IdKorisnika"] }, new { @class = "btn btn-info" })
<br />
<br />
<table class="table">
    <tr>
        <th>
            Naziv
        </th>
        <th>
            Reziser
        </th>
        <th colspan="2">
            Datum
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.Kolicina)
            </th>*@
    </tr>
    @foreach (var item in Model.Where(i => i.RedniBrojČlana == (int)Session["IdKorisnika"]))
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Naziv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Reziser)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Datum)
            </td>
            <td>
                @Html.ActionLink("Obriši rezervaciju", "Delete", "IznajmljeneFilms", new { id = item.RedniBrojIznajmljivanja }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }
</table>
<div>
    @Html.PagedListPager(Model, strana => Url.Action("Index", new { strana = strana }))
</div>